version: "3.8"

services:
  mobile-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: mobile-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Use your existing PostgreSQL on localhost:5432
      - DATABASE_URL=postgres://appuser:apppass@host.docker.internal:5432/appdb?sslmode=disable
      - REDIS_URL=redis:6379
      - JWT_SECRET=your_super_secret_jwt_key_change_this_in_production
      - GIN_MODE=release
      - LOG_LEVEL=info
      - CORS_ALLOWED_ORIGINS=*
    depends_on:
      - redis
    networks:
      - mobile-backend-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7-alpine
    container_name: mobile-backend-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mobile-backend-network

volumes:
  redis_data:
    driver: local

networks:
  mobile-backend-network:
    driver: bridge
