version: "3.8"

services:
  mobile-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: mobile-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://appuser:apppass@postgres:5432/appdb?sslmode=disable
      - REDIS_URL=redis:6379
      - JWT_SECRET=your_super_secret_jwt_key_change_this_in_production
      - GIN_MODE=release
      - LOG_LEVEL=info
      - CORS_ALLOWED_ORIGINS=*
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mobile-backend-network

  postgres:
    image: postgres:15-alpine
    container_name: mobile-backend-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppass
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mobile-backend-network

  redis:
    image: redis:7-alpine
    container_name: mobile-backend-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mobile-backend-network

networks:
  mobile-backend-network:
    driver: bridge
